<%@ page contentType="text/html;charset=UTF-8"%>
<meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />
<meta name="keywords" content="华房网，合肥华房网络科技有限公司，合肥房产网，房产信息网，合肥最新楼盘，合肥团购楼盘"/>
<meta name="description" content=""/>
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
<link rel="stylesheet"  href="web/css/global.css" />
<link rel="stylesheet"  href="web/css/index.css" />
<link rel="stylesheet" media="all" href="web/css/list_details.css"/>
<link rel="stylesheet" media="all" href="web/css/article2.css"/>
<script type="text/javascript" src="js/jquery-1.9.1.min.js"></script>
<script type="text/javascript" src="js/layer/layer.js"></script>
<script type="text/javascript" src="js/common.js"></script>	
<script type="text/javascript" src="web/js/fun.js"></script>
<script type="text/javascript" src="web/js/map.js"></script>

